spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: r1
              uri: http://localhost:8090
              predicates:
                - Path= /api/keynotes/**
            - id: r2
              uri: http://localhost:8091
              predicates:
                - Path= /api/conferences/**

